version: '3.8'

services:
  db:
    image: mysql:8
    container_name: dbKosmoeye
    restart: always
    environment:
      MYSQL_DATABASE: kosmoeye_db
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: kosmoeye
      MYSQL_PASSWORD: kosmoeye123
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kosmoeye-net

volumes:
  db_data:

networks:
  kosmoeye-net:
    driver: bridge
